import React from 'react';
import Head from 'next/dist/next-server/lib/head';
import styled from 'styled-components';
import Image from 'next/dist/client/image';
const Showcase = ({ heroes }) => {
  return (
    <>
      <Head>
        <title>Showcase</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {heroes.map((hero, index) => (
        <ShowcaseStyles id='showcase' key={index}>
          <h1 className='showcase-title'>Elegant Taste</h1>
          <div className='showcase-content'>
            <div className='image-side'>
              <Image
                src={hero.showcase_image.url}
                alt={hero.showcase_image.name}
                width={500}
                height={500}
              />
            </div>
            <div className='statement-side'>
              <p>{hero.showcase_text}</p>
            </div>
          </div>
        </ShowcaseStyles>
      ))}
    </>
  );
};
const ShowcaseStyles = styled.div`
  width: 100%;
  min-height: 50vh;
  background: url(/images/darkBg.png) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  font-family: 'Quicksand', sans-serif;
  background-size: cover;

  .showcase-title {
    font-size: 2.5rem;
    text-align: center;
    padding: 20px auto;
    color: #e1c089;
  }
  .showcase-content {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    justify-content: center;
    align-items: center;
  }

  .image-side img {
    width: 80%;
    display: block;
    margin: auto;
  }

  .statement-side p {
    color: #e1c089;
    font-size: 1.2rem;
    text-align: left;
    line-height: 1.5;
    padding: 15px;
    margin: 15px;
    background: rgb(99, 79, 53, 0.3);
    border-radius: 5px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px,
      rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;
  }

  @media only screen and (max-width: 768px) {
    .showcase-content {
      grid-template-columns: repeat(1, 1fr);
    }

    .statement-side p {
      text-align: center;
    }
  }
`;
export default Showcase;
