import React from 'react';
import styled from 'styled-components';
import Head from 'next/dist/next-server/lib/head';
import Image from 'next/dist/client/image';
const Testimonials = () => {
  return (
    <>
      <Head>
        <title>Testimonials</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TestimonialsStyles id='testimonials'>
        <h1 className='heading'>Testimonials</h1>
        <div className='cards-container'>
          <div className='testimonial-card'>
            <Image src='/images/person.jpg' alt='' width={500} height={500} />
            <h4>Allen</h4>
            <p className='comments'>The taste is exceptional</p>
            <small className='date'>20/1/2021</small>
          </div>
          <div className='testimonial-card'>
            <Image
              src='/images/jennifer-schmidt-gHm50qaMaXc-unsplash.jpg'
              alt=''
              width={500}
              height={500}
            />
            <h4>Karen</h4>
            <p className='comments'>
              Id buy the Choclate cake over and over again
            </p>
            <small className='date'>09/11/2019</small>
          </div>
          <div className='testimonial-card'>
            <Image
              src='/images/pexels-yogendra-singh-3748221.jpg'
              alt=''
              width={500}
              height={500}
            />
            <h4>UH9</h4>
            <p className='comments'>Their cakes are literally awesome</p>
            <small className='date'>13/09/2020</small>
          </div>
        </div>
      </TestimonialsStyles>{' '}
    </>
  );
};
const TestimonialsStyles = styled.div`
  width: 100%;
  position: relative;
  min-height: 100vh;
  background: url(/images/henry-co-tqu0IOMaiU8-unsplash.jpg) no-repeat center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  font-family: 'Quicksand', sans-serif;
  background-size: cover;

  .heading {
    text-align: center;
    font-size: 3rem;
    color: #634f35;
    padding: 30px;
  }
  .cards-container {
    margin: 10px;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
  }

  .testimonial-card {
    background: #634f35;
    color: #fff;
    display: flex;
    justify-content: center;
    flex-direction: column;
    grid-gap: 10px;
    margin: 5px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px,
      rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;
  }

  .testimonial-card img {
    width: 25%;
    display: block;
    padding: 10px;
    border-radius: 50%;
    margin: auto;
  }
  .testimonial-card h4 {
    text-align: center;
  }
  .testimonial-card .comments {
    line-height: 1.4;
    color: #fff;
    font-size: 1.3rem;
    font-weight: 300;
    padding: 10px;
  }
  .testimonial-card small {
    text-align: center;
    margin: 10px;
    color: #7a756b;
  }

  @media screen and (max-width: 671px) {
    .cards-container {
      grid-template-columns: repeat(1, 1fr);
      grid-template-rows: repeat(3, 1fr);
    }
  }
`;
export default Testimonials;
